### ISSUE TITLE
Create a detached behat runner

### ISSUE THREAD

**Issue by carlosV2** [carlosV2/bash-dev-tools#18]
When you run behat, you often need to wait until it completes before changing the git branch, modifying files, etc (this, actually makes sense). Although this is an acceptable behaviour, sometimes, it takes a lot of time to complete. You could better use this time to review anybody branch or to start another branch.

The idea is to implement a detached behat runner. It should duplicate project into a temporary folder and run behat from it so the original project folder is free to continue working.

**Comment by carlosV2** [comment]
A phpspec detached runner would be appreciated too.

**Comment by carlosV2** [comment]
Added into commit https://github.com/carlosV2/bash-dev-tools/commit/4c7b897c297bd1d589d63f156513b5226a630f2c.

I'm keeping this issue as a reminder to create the phpspec one.

**Comment by DavidGarciaCat** [comment]
A PHPUnit detached runner would be appreciated too :smiley_cat: 

Cheers,

**Comment by carlosV2** [comment]
The commit https://github.com/carlosV2/bash-dev-tools/commit/74473b1925d14dd5dac13b04638886f70859dcd9 brings an evolution of the detach mechanism.

I've removed this mechanism from behat and make it systemwide available.
The new command supports any bash command (including PHPSpec, Behat, PHPUnit, etc).

I'm closing this issue as the requested functionality is now provided.
