### ISSUE TITLE
The "--fixers" option does not exist.

### ISSUE THREAD

**Issue by DavidGarciaCat** [carlosV2/bash-dev-tools#19]
I have just updated my current version of PHP CS Fixer (from `^1.11` to `2.0-dev`) to test the new `dev` version, and I have got this message:

```
[Symfony\Component\Console\Exception\RuntimeException]
The "--fixers" option does not exist.
```

The command displays these valid arguments too:

```
fix
    [--allow-risky ALLOW-RISKY]
    [--config-file [CONFIG-FILE]]
    [--dry-run]
    [--rules RULES]
    [--using-cache USING-CACHE]
    [--cache-file CACHE-FILE]
    [--diff]
    [--format FORMAT]
    [--]
    [<path>]
```

It happens just when I want to fix the `PHP Spec` files, given the `PHP Spec fixer` wants to skip the `visibility` ([affected line here](https://github.com/carlosV2/bash-dev-tools/blob/master/phpspectools.sh#L6))

**Comment by DavidGarciaCat** [comment]
This is the `2.0-dev` version that I have:

```
$ composer show -i | grep fabpot
fabpot/php-cs-fixer dev-master 2ac4bdb A tool to automatically fix PHP code style
```

**Comment by carlosV2** [comment]
Is this fixed?

**Comment by DavidGarciaCat** [comment]
Should be - Didn't find an error after all these time 😅
